spring:
  profiles:
    active: dev
  web:
    resources:
      add-mappings: true
  mvc:
    cors:
      allowed-origins: "http://localhost:5173"
      allowed-methods: GET, POST, PUT, DELETE, PATCH
      allowed-headers: "*"
      allow-credentials: true

  quartz:
    job-store-type: memory
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/batch/core/schema-mysql.sql

  datasource:  # 배치 작업(도메인) 데이터 DB
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/traffic_info
    username: root
    password: root


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

#mybatis:
#  mapper-locations: classpath:Mappers/*.xml
#  configuration:
#    map-underscore-to-camel-case: true
server:
  address: 0.0.0.0
  port: 8080

logging.level:
  org.hibernate.SQL: trace
  org.hibernate.type: trace
  org.quartz: debug

