name: Auto PR to main

on:
  push:
    branches-ignore:
      - 'main'       # main 브랜치만 트리거에서 제외
jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃
        uses: actions/checkout@v3

      - name: PR 자동 생성(main 기준)
        uses: peter-evans/create-pull-request@v6
        with:
          base: main
          branch: ${{ github.ref_name }}
          title: 'Auto PR: ${{ github.ref_name }} → main'
          body: '자동화된 PR: ${{ github.ref_name }} 브랜치를 main에 머지합니다.'